services:
  flask:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  nginx:
    build:
      context: ./frontend
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - flask
      - db