services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: cafe_db
      POSTGRES_USER: flask_server
      POSTGRES_PASSWORD: abc123
    volumes:
    - ./db:/docker-entrypoint-initdb.d:ro
    ports: 
    - "5432:5432"